#!/bin/env python3

# IMPORTANT! THIS IS ONLY AN EXAMPLE SCRIPT!
# DO NOT USE THIS DIRECTLY FOR MORE EFFICENT PRIVACY!
# BECAUSE THIS CODE IS VERY EASY TO BREAK AND OPENSOURCE!
# YOU CAN RE-WRITE THE FUNCTIONS WITHIN SAME FILENAME.
# USE THE SAME FUNCTION NAMES.

def en(code:str):
	return f"salt{code[::-1]}salt"
def de(code:str):
    return code[4:-4][::-1]
